name: Scheduled Job

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.2
      - uses: actions/setup-node@v2.5.2
        with:
          node-version: "16"
      - run: npm install
      - run: backend/index.js
